---
title: "Weixuan_Chen_hw2"
author: "Weixuan Chen"
date: "1/21/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

## 1

```{r}

my_mean <- function(x){
  sum <- 0
  size <- length(x)
  for(value in x){
    sum <- sum + value
  }
  
  return(sum/size)
}

```

## 2

```{r}

is_greater <- function(x){
  if (length(x) == 4){
      if (x[1] + x[2] > x[3] + x[4]){
        return(x)
      }
      else{
        return(0)
      }
  }
  else{
    return(0)
  }
}

```

## 3

```{r}

my_fibonacci <- function(n){
  if(n == 1){
    return(c(1))
  }
  else if(n == 2){
    return(c(1,1))
  }
  else{
    fib <- c(1,1)
    size <- 2
    while (size < n) {
      fib[size + 1] <- fib[size - 1] + fib[size]
      size <- size + 1
    }
    
    return(fib)
  }
}

```

## 4

```{r}

m <- matrix(data = 1:16, nrow = 4, ncol = 4, byrow = TRUE)
m
apply_m <- apply(m, 1, my_mean)
apply_m

```

## Question 2

## 1

```{r}
max_wind_ozone <- aggregate(cbind(Wind, Ozone) ~ Month, data = airquality, "max")
max_wind_ozone
```

## 2

```{r}

authors <- data.frame(surname = c("Tukey", "Venables", "Tierney", "Ripley", "McNeil"), 
    nationality = c("US", "Australia", "US", "UK", "Australia"), stringsAsFactors = FALSE)

books <- data.frame(name = c("Tukey", "Venables", "Tierney", "Ripley", "Ripley", 
    "McNeil", "R Core"), title = c("Exploratory Data Analysis", "Modern Applied Statistics ...", 
    "LISP-STAT", "Spatial Statistics", "Stochastic Simulation", "Interactive Data Analysis", 
    "An Introduction to R"), stringsAsFactors = FALSE)

merge.data.frame(authors, books, by.x = "surname", by.y = "name")

```

## 3

```{r}

my_sentence <- "To be, or not to be -- that is the question: Whether 'tis nobler in the mind to suffer  The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles, And by opposing end them. To die -- to sleep -- No more..."
gsub("[T|t]o", 2, my_sentence)

```

## Question 3

## 1

```{r}
#data(iris)
head(iris)

hist(iris$Sepal.Length, main = "Frequencies of sepal length in each numerical interval", xlab = "Length of Sepal")

```

## 2

```{r}
plot(iris$Petal.Length, y = iris$Petal.Width, main = "Distribution of iris by the feature pedal", xlab = "Pedal Length", 
    ylab = "Pedal Width")
```

## 3

```{r}
library(tidyverse)

mtc <- mutate(mtcars,cyl=factor(cyl,ordered=TRUE,levels=c(4,6,8)))
head(mtcars,n=6)

ggplot(mtc,aes(x=mpg)) + geom_histogram(binwidth=5) + xlab('Miles per Gallon')+ylab('Number of Cars') 

```
## 4

```{r}

ggplot(mtc,aes(x=cyl,y=mpg)) + geom_boxplot() + xlab('Cylinders') + ylab('Miles per Gallon') + coord_flip()

```
## 5

```{r}

ggplot(mtc,aes(x=wt,y=mpg)) + geom_point() + xlab('Weight (x 1000lbs)') + ylab('Miles per Gallon') + geom_smooth()

```

